# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Temporary Obsessions
tagline:          'A Miscellany'
description:      'Things I got obsessed about, wrote about, and
possibly moved on from.'
url:              http://treese.github.io
baseurl:          /

author:
  name:           'Win Treese'
  url:            https://twitter.com/wintreese

paginate:         5

# Custom vars
version:          2.1.0
gems: [jekyll-paginate]

github:
  repo:           https://github.com/poole/hyde
